---
purpose: development
ocp4_workload_showroom_antora_enable_dev_mode: "true"

__meta__:
  access_control:
    allow_groups:
      - rhpds-devs
  catalog:
    display_name: "Govern AI Model Access with Praxis (Dev)"
  sandboxes:
    - kind: OcpSandbox
      cloud_selector:
        purpose: dev
        cloud: cnv-dedicated-shared
        lab: ai-qs-intel-inference
