---
__meta__:
  catalog:
    display_name: "Govern AI Model Access with Praxis (Dev)"
    labels: [dev, partner-intel]
  components:
    - name: cluster
      parameter_values:
        num_users: 1
        worker_instance_count_formula: "2"
  deployer:
    execution_environment: quay.io/agnosticd/ee-multicloud:chained-latest
lifetime: 4h
max_lifetime: 8h
