---
purpose: development
num_users: 1
ocp4_workload_showroom_antora_enable_dev_mode: "true"

__meta__:
  access_control:
    allow_groups:
      - rhpds-devs
  catalog:
    display_name: "Govern AI Model Access with Praxis (Dev)"
  components:
    - name: openshift
      parameter_values:
        cluster_size: multinode
        host_ocp4_installer_version: "4.20"
